### ISSUE TITLE
.gitignore/.hgignore should be updated to prevent accidentally adding secrets

### ISSUE THREAD

**Issue by TomOnTime** [StackExchange/blackbox#10]
blackbox_register_new_file should add the file to .gitignore or .hgignore as appropriate.

I believe the syntax is different for each of those, so I'd appreciate pointers on what the format should be for each.  In particular, we want to block path/path/foo but not path/path/foo.gpg (and not other/path/foo)

**Comment by tlimoncelli** [comment]
This has been implemented for HG for a while.
