### ISSUE TITLE
File permissions do not persist

### ISSUE THREAD

**Issue by nathanielks** [StackExchange/blackbox#100]
Currently, whenever a file is added to the registry, `filename.txt.gpg` will be created and saved with 644 permissions. When it's decrypted, same story, 644. I'd like to be able to have whatever the permissions were at time of encryption persist through the process, so if I have something set to 600, it gets decrypted to 600.

**Comment by tlimoncelli** [comment]
Would it be sufficient to set the perms on the decrypted file to match the perms on the .gpg file?

The decrypt function could:
`chmod --reference filename.txt.gpg filename.txt`

We could probably do something similar when registering the file.

Reference:
http://unix.stackexchange.com/questions/20645/clone-ownership-and-permissions-from-another-file

**Comment by nathanielks** [comment]
yup, that'd work great!

**Comment by wiredmax** [comment]
That would be so great and would remove the bad permissions with SSH/SCP warning us that the private key is unprotected when the permissions are 644 when decrypted instead of 600.

**Comment by tlimoncelli** [comment]
That should do it.  Re-open this ticket if it doesn't work.

**Comment by tlimoncelli** [comment]
Sadly this breaks on MacOS.  I'm working on a patch.

**Comment by tlimoncelli** [comment]
Fixed in aee22fc

**Comment by wiredmax** [comment]
Awesome! :tada:

**Comment by mig8447** [comment]
This is not working on homebrew blackbox version 1.20181219 (macOS 10.14.4, GPG 2.1) for a file that has 400 permissions. When decrypting, it stores the file as 644
