### ISSUE TITLE
blackbox_deregister_file is missing from release tar

### ISSUE THREAD

**Issue by amosshapira** [StackExchange/blackbox#103]
The README file mentions that the way to remove a file from the system is to run `blackbox_deregister_file` but this script isn't available in the latest release .tar.

Perhaps it's time to have a new release?

**Comment by tlimoncelli** [comment]
The manifest files for the packages were missing that.  Thanks for pointing that out!

Fixed in https://github.com/StackExchange/blackbox/commit/6765988274674a538a9b09428f754fd3f2d2e2a0

**Comment by amosshapira** [comment]
Thanks for the quick fix.
