### ISSUE TITLE
Unable to initialize new repository with blackbox_initialize

### ISSUE THREAD

**Issue by rfein-hearst** [StackExchange/blackbox#105]
Using 6765988274674a538a9b09428f754fd3f2d2e2a0 - any attempt to get initialize a repository fails. Works fine using a much older version 

$ blackbox_initialize 
Enable blackbox for this git repo? (yes/no) yes
ERROR: <path> is not a blackbox Repo

**Comment by selfcommit** [comment]
Looks like the problem is in the call to change_to_vcs_root in blackbox_initialize

`change_to_vcs_root` will error if the repo is not already a blackbox Repo

    # chdir to the base of the repo.
    function change_to_vcs_root() {
      # if vcs_root not explicitly defined, use $REPOBASE

      local rbase=${1:-$REPOBASE} # use $1 but if unset use $REPOBASE

      if ! is_blackbox_repo "$rbase"; then
        echo "ERROR: $rbase is not a blackbox Repo"
        exit 1
      fi
    }

Proposing a fix shortly

**Comment by selfcommit** [comment]
@tlimoncelli Confidence test is resolved.  Waiting on your ok to merge this.

**Comment by selfcommit** [comment]
@rfein-hearst please confirm this is resolved for you in the latest build
