### ISSUE TITLE
"make confidence" on Mac asks for password too much

### ISSUE THREAD

**Issue by TomOnTime** [StackExchange/blackbox#108]
The use of gpg-agent seems to be broken on Mac OS X.

become_alice and become_bob don't seem to work.  The "a" and "b" passwords have to be entered over and over again.

Every time it asks for a password, it first prints:

```
can't connect to `/tmp/gpg-xhWU7m/S.gpg-agent:5356:1': No such file or directory
gpg: can't connect to `/tmp/gpg-xhWU7m/S.gpg-agent:5356:1': connect failed
```

gpg (GnuPG) 1.4.19
gpg-agent (GnuPG) 2.0.28
pinentry-curses (pinentry) 0.9.4

**Comment by tlimoncelli** [comment]
Fixed in 48cc17ac0a7622c3bacc109e34ed8d5ff58a3690
