### ISSUE TITLE
"make confidence" on Linux asks for password after switching users

### ISSUE THREAD

**Issue by TomOnTime** [StackExchange/blackbox#109]
"make confidence" uses gpg-agent so that the password doesn't have to be entered over and over.

However, it does ask for Alice's password once after switching Bob->Alice and vice-versa.  It isn't clear to me what about become_alice and become_bob is broken that makes that happen.

It would be great if it only asked for Alice's password exactly once, and Bob's password exactly once.

**Comment by tlimoncelli** [comment]
Fixed in 48cc17ac0a7622c3bacc109e34ed8d5ff58a3690
