### ISSUE TITLE
FR: "blackbox_edit FILE" should encrypt if not already encrypted, and call $EDITOR

### ISSUE THREAD

**Issue by TomOnTime** [StackExchange/blackbox#11]
It would be convenient to just be able to type "blackbox_edit FILE" and not have to think about the entire process:

Is the file encrypted already?
  No: Ask "are you sure?" and then blackbox_register_new_file.
  Yes: decrypt.
Call $EDITOR
Was "-d" option specified?"
  Yes: Re-encrypt and delete the plaintext version.
  No: Re-encrypt and leave the plaintext version alone. Output instructions on how to safely shred it.

**Comment by tlimoncelli** [comment]
I'm resolving this without the "-d" flag implemented. If you want the -d flag, just use blackbox_edit_start.
