### ISSUE TITLE
"make confidence" shouldn't be interactive

### ISSUE THREAD

**Issue by TomOnTime** [StackExchange/blackbox#110]
"make confidence" pauses to ask for passwords. It shouldn't.

GPG makes it very difficult to supply passphrase automatically... which is a very smart decision in general. However it makes automated testing a pain.

Maybe someone can make a very stupid pinentry clone that gives "a" as the password for alice, and "b" as the password for bob.

**Comment by selfcommit** [comment]
Are you OK with using face keys that have no pass-phrase? They Keys could be generated without a passphrase, avoiding the need for one to be entered.
Automating key entry would be particularly tough on OSX, as GPG tools creates a box outside the terminal.

**Comment by TomOnTime** [comment]
My requirement is that it works for both positive and negative testing. That is, if Alice is active, Alice stuff should work and Bob stuff should fail. If Bob is active, Bob stuff should work and Alice stuff should fail.  I want a hard failure if someone does something that they shouldn't be allowed to do.  I don't think that can happen if there is no password.  However, I'm willing to be proven wrong. :-)

**Comment by tlimoncelli** [comment]
Fixed with 48cc17ac0a7622c3bacc109e34ed8d5ff58a3690
