### ISSUE TITLE
Is it possible to do another release?

### ISSUE THREAD

**Issue by cintiadr** [StackExchange/blackbox#112]
Last release was more than a month ago, and there are quite a few changes included. 

I know I can clone the repository and use the bin folder, or even store the artifacts somewhere else, but I need some of the bug fixes and having a new release in https://github.com/StackExchange/blackbox/releases would be awesome. 

Is there any idea when that will happen?

**Comment by tlimoncelli** [comment]
I've marked the current HEAD as "stable" and, per the guidelines in RELEASE_ENGINEERING.txt, I will now wait 1 week and promote that to "production" if no new bugs are discovered.

**Comment by cintiadr** [comment]
Thanks :)

**Comment by tlimoncelli** [comment]
Release done.  MacPorts updated.
