### ISSUE TITLE
mktemp: too few X's in template ‘_stacklib_’ (again)

### ISSUE THREAD

**Issue by daniel-barlow** [StackExchange/blackbox#113]
The `mktemp` command in GNU coreutils, when given a -t argument, expects it to contain at least three consecutive `X` characters

It looks like you added a fix for this in https://github.com/StackExchange/blackbox/commit/56232aafc895311d97572e624ed1813825bc3b34 then subsequently clobbered it in https://github.com/StackExchange/blackbox/commit/02700b547a80a014ee8fb1b66e8c586e0489bc2c

 \- can you restore it please?  Sorry no patch as I don't understand the code well enough to know what the difference is between `make_self_deleting_tempfile` and `create_self_deleting_tempfile`

(NB: Consulting manual pages on both MacOS and Linux suggests that both OSes will accept `-t _stacklib_.XXXXX` so there should be no need here to switch on `uname`)

**Comment by tlimoncelli** [comment]
I've fixed the regression. Thanks for noticing that!
