### ISSUE TITLE
Cygwin addadmin function immediately returns with Unknown OS error

### ISSUE THREAD

**Issue by bignis** [StackExchange/blackbox#114]
I am using Blackbox's Production release (https://github.com/StackExchange/blackbox/commit/343b85a34cbfc9bca7458bbf660eeb7c940d25f4) on Cygwin on Windows 8 and going through the first time setup.

When running the addadmin function, I get an "ERROR: Unknown OS. Exiting.".

```
u0044975@U0044975-TPL-C /cygdrive/c/code/meetingtimesuggester
$ blackbox_addadmin bignis@gmail.com
ERROR: Unknown OS. Exiting.

u0044975@U0044975-TPL-C /cygdrive/c/code/meetingtimesuggester
$ uname -s
CYGWIN_NT-6.2

u0044975@U0044975-TPL-C /cygdrive/c/code/meetingtimesuggester
```

**Comment by TomOnTime** [comment]
A recent change broke cygwin compatibility.  This commit (https://github.com/StackExchange/blackbox/commit/7c7300946148790cf185ae47452e072ae0d87c2a) should fix it.

**Comment by bignis** [comment]
yep, no longer get the error, thanks!
