### ISSUE TITLE
remove (unnecessary) python dependency

### ISSUE THREAD

**Issue by JanTvrdik** [StackExchange/blackbox#115]
Currently there is a [single line depending on python](https://github.com/StackExchange/blackbox/blob/7c7300946148790cf185ae47452e072ae0d87c2a/bin/_blackbox_common.sh#L332). It would be nice to remove  this unnecessary dependency entirely or make it optional.

**Comment by tlimoncelli** [comment]
Is this hypothetical or is this preventing blackbox from running on a particular OS?

**Comment by JanTvrdik** [comment]
I does not prevent me from running blackbox but it makes the installation more difficult (because I need to install python or modify the line). The python requirement is also not mentioned in readme so I found out about it by running blackbox and receiving error which is not very friendly.

**Comment by JanTvrdik** [comment]
Thank you!
