### ISSUE TITLE
.gitignore gets updated when I blackbox_register_new_file, but not added to the commit

### ISSUE THREAD

**Issue by unixorn** [StackExchange/blackbox#119]
I run `blackbox_register_new_file foo`, and after it does the dance and the file is encrypted and added to the repo with a commit automatically, `git-repo-root-directory/.gitignore` is updated as expected, but it isn't actually committed in the same automatic commit that foo.gpg was.

I work around it by `git commit --amend .gitignore`, but it would be better if the .gitignore change was included in the automatic `* registered in blackbox: path/to/foo` commit

**Comment by allonhadaya** [comment]
I can confirm this behavior... Looks like this functionality was introduced [here](https://github.com/StackExchange/blackbox/pull/25/files?diff=unified#diff-ad3be58486277ee989293500158f5c88R54), but removed [here](https://github.com/StackExchange/blackbox/commit/01e681035dc3cb874215e6cff947246f644f200c#diff-ad3be58486277ee989293500158f5c88L58). It seems like this should be supported by making [vcs_ignore](https://github.com/StackExchange/blackbox/blob/master/bin/_blackbox_common.sh#L552) a little smarter. It never adds the ignore file.

**Comment by allonhadaya** [comment]
On second thought, it looks like [this line](https://github.com/StackExchange/blackbox/blob/master/bin/_blackbox_common.sh#L586) is supposed to have this covered... Not sure what's going on.

**Comment by allonhadaya** [comment]
I was able to do a little more sleuthing.

    /tmp/project$ blackbox_register_new_file foo

It turns out that `vcs_add_git` is not designed to add a file that's already being tracked to staging:

    ...
    + vcs_add /tmp/project/.gitignore
    + vcs_add_git /tmp/project/.gitignore
    + git add /tmp/project/.gitignore
    + echo 'NOTE: "already tracked!" messages are safe to ignore.'
    NOTE: "already tracked!" messages are safe to ignore.
    ...

So rather than actually add .gitignore to the subsequent commit, it's letting us know that it's "already tracked!". I haven't had the time to read the code, but I figured I'd leave a hint here for me or anyone else who wants to continue digging.

**Comment by tlimoncelli** [comment]
Would this fix it?  https://github.com/StackExchange/blackbox/pull/132
(I haven't tested this directly)

**Comment by tlimoncelli** [comment]
I think that covers it.  Please re-open if it doesn't.
