### ISSUE TITLE
gpg-agent doesn't work with 

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/blackbox#126]
@snowpong noticed that blackbox_decrypt_all_files does not work on Git for Windows. It fails with:

    ../blackbox/bin/blackbox_decrypt_all_files: line 19: gpg-agent: command not found
    ../blackbox/bin/blackbox_decrypt_all_files: line 22: exec: blackbox_postdeploy: not found

**Comment by tlimoncelli** [comment]
Is gpg-agent not installed?  Then the script should print a warning and exit.

Is gpg-agent installed?  We should verify that it works.

**Comment by billrawlinson** [comment]
sorry I commented initially on #125.

After installing GpG4Win and then adding `C:\Program Files (x86)\GNU\GnuPG` to my path gpg-agent exists in mingw
