### ISSUE TITLE
`make confidence` fails on El Capitan

### ISSUE THREAD

**Issue by adityamarella** [StackExchange/blackbox#129]
#> git clone https://github.com/StackExchange/blackbox.git && cd blackbox
#> make confidence

-----
....
You need a passphrase to unlock the secret key for
user: "Bob Example (my password is the lowercase letter b) <bob@example.com>"
2048-bit RSA key, ID 8194047C, created 2015-11-12 (main key ID 0ED38B6D)

========== EXTRACTED secret.txt
========== Decrypting new/changed files: DONE
ASSERT FAILED: secret.txt chgrp wanted=110214070 found=(110214070)
make: *** [confidence] Error 1

**Comment by TomOnTime** [comment]
It works for me.  Can you try again?

**Comment by tlimoncelli** [comment]
Since this works for me, please re-open this issue if you find it to still not work.

**Comment by adityamarella** [comment]
Still fails for me with the same error. 

========== EXTRACTED secret.txt
========== Decrypting new/changed files: DONE
**ASSERT FAILED: secret.txt chgrp wanted=110214070 found=(110214070)**
make: *** [confidence] Error 1

**Comment by tlimoncelli** [comment]
What operating system are you using?

**Comment by adityamarella** [comment]
Mac OS X El Capitan 10.11.3

**Comment by TomOnTime** [comment]
Duh. That was in the subject line, wasn't it?

Odd, I run El Cap as my main development machine. 

I've checked in a version of tools/test_functions.sh with some extra debug print statements.  Can you "git pull" and run "make confidence" again?  Once it fails, send me the last 40 lines of output.

I think that "stat" is outputting numbers surrounded by ()'s for you, but not for me.  I'm trying to figure out why that is so.

Tom

**Comment by adityamarella** [comment]
@TomOnTime  thanks for looking into this. 

This was working on Yosemite. It stopped working after I upgraded to El Capitan. And yeah the OS is already mentioned in bold in the subject line.

Here is the output 
> You need a passphrase to unlock the secret key for
> user: "Alice Example (my password is the lowercase letter a) <alice@example.com>"
> 2048-bit RSA key, ID BC48751F, created 2016-03-15 (main key ID 1C96AB29)
> 
> ********************
> ********************
> ********* appears.
> ********************
> ********************
> ********************
> ********************
> ********* Bob makes sure he has all new keys.
> ********************
> ********************
> gpg: key 1C96AB29: public key "Alice Example (my password is the lowercase letter a) <alice@example.com>" imported
> gpg: key C661897A: "Bob Example (my password is the lowercase letter b) <bob@example.com>" not changed
> gpg: Total number processed: 2
> gpg:               imported: 1  (RSA: 1)
> gpg:              unchanged: 1
> DEFAULT_GID_NAME=110214070
> TEST_GID_NUM=21160883
> TEST_GID_NAME=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ********************
> ********************
> ********* Bob postdeploys... default.
> ********************
> ********************
> ========== Importing keychain: START
> gpg: Total number processed: 2
> gpg:              unchanged: 2
> ========== Importing keychain: DONE
> ========== Decrypting new/changed files: START
> 
> You need a passphrase to unlock the secret key for
> user: "Bob Example (my password is the lowercase letter b) <bob@example.com>"
> 2048-bit RSA key, ID F04475A2, created 2016-03-15 (main key ID C661897A)
> 
> ========== EXTRACTED secret.txt
> ========== Decrypting new/changed files: DONE
> DEBUG: assert_file_group X110214070X vs. X(110214070)X
> DEBUG: /usr/bin/stat
> ASSERT FAILED: secret.txt chgrp group wanted=110214070 found=(110214070)
> make: *** [confidence] Error 1

Here is the output of stat on LICENSE.txt (if this helps)

> 16777220 36514383 -rw-r--r-- 1 aditya (110214070) 0 1092 "Mar 15 16:36:39 2016" "Mar 14 18:08:59 2016" "Mar 14 18:08:59 2016" "Mar 14 18:08:59 2016" 4096 8 0 LICENSE.txt

**Comment by TomOnTime** [comment]
I've never seen the 6th item in stat to be in parenthesis.  The man page doesn't mention anything about it, but I found http://www.opensource.apple.com/source/file_cmds/file_cmds-220.7/stat/stat.c which indicates that if the numeric-to-string function fails, it substitutes the decimal number surrounded by parens.  I can demonstrate this on FreeBSD and MacOS X.  Mystery solved!

However now we need a clean way to fix this.

I've rewritten the tests to use group id instead of group name.  See if that works.

Tom
