### ISSUE TITLE
Public key expired for an admin.  Need to remove and add again?

### ISSUE THREAD

**Issue by chishaku** [StackExchange/blackbox#133]
An admin's public key expired so now I can't re-encrypt files.  

Do I need to remove the admin and have them added again with their new or modified key?

I'm a bit confused on the workflow.  Thanks in advance.

**Comment by tlimoncelli** [comment]
Gosh I'm not sure what to suggest.  I haven't had to do this process yet. My guess is that you would do:

One way would be to decrypt everything with the old key, change keys, then re-encrypt:

""""
eval $(gpg-agent --daemon)          # If you don't already have an agent running.
blackbox_decrypt_all_files
(update the key)
for i in $(blackbox_list_files) ; do echo blackbox_edit_end "$i" ; done
(test to make sure things are correct before you check them in)
"""

Would you do me a favor and try this?  Keep good notes and report back.  I will turn your notes into an item for the FAQ and it will help others that have this problem.

Tom

**Comment by chishaku** [comment]
Here's what I ended up doing:

**Step 0**

```
blackbox_edit_end modified_file.txt
--> Error: can't re-encrypt because a key has expired.
```

**Step 1. Administrator removes expired user**

```
blackbox_removeadmin expired_user@example.com
# Temporarily rename any modified files so they're not replaced by the next command.
blackbox_update_all_files
git commit -m "Re-encrypt all files"
gpg --homedir=keyrings/live --delete-key expired_user@example.com
git commit -m 'Cleaned expired_user@example.com from keyring'  keyrings/live/*
git push
```

**Step 2. Expired user adds an updated key**

```
git pull
blackbox_addadmin updated_user@example.com
git commit -m'NEW ADMIN: updated_user@example.com keyrings/live/pubring.gpg keyrings/live/trustdb.gpg keyrings/live/blackbox-admins.txt
git push
```

**Step 3. Administrator re-encrypts all files with the updated key of the expired user**

```
git pull
gpg --import keyrings/live/pubring.gpg 
blackbox_update_all_files 
git commit -m "Re-encrypt all files"
git push
```

**Last step**

Any files that were temporarily renamed in the first step so as to not be overwritten can now be renamed to their original name and re-encrypted with the `blackbox_edit_end` command.

**Comment by tlimoncelli** [comment]
Thanks for the most excellent documentation!  (and I know it is excellent because your style is very similar to mine!)

I've included this in the readme: https://github.com/StackExchange/blackbox/commit/f7a159d685c4af26c4c811a6e1599b8037ac602f
