### ISSUE TITLE
not found in keyrings/live/blackbox-files.txt

### ISSUE THREAD

**Issue by mdumouchel** [StackExchange/blackbox#135]
I'm getting the following
ERROR: theFile.json not found in /fullpath/keyrings/live/blackbox-files.txt

blackbox-files.txt has the following
theFile.json

The paths all appear to be correct.  Everyone else in the team can decrypt this file.  Additionally we are using blackbox in another project which works fine for everyone including myself.

**Comment by tlimoncelli** [comment]
That's quite odd.  Are you using a filesystem that is case insensitive (Mac OS X, for example)?

What's the output of this:

`$ fgrep theFile.json /fullpath/keyrings/live/blackbox-files.txt`

Are there any funny tabs, new lines, or spaces in the filename and/or blackbox-files.txt?

**Comment by mdumouchel** [comment]
Yes I am on a mac.  The rest team is also on a mac.  When I do the fgrep command i get back theFile.json

There was a second line in the file I removed it but got the same results. 

Some more information on how I got to this state.  I first added the file and a user from the group registered the file again and change the path.  It was originally something like this ../dir/theFile.json they made it just theFile.json.  The file didn't move to a new directory just the path changed.

With that I can change the blackbox-files.txt back to ../dir/theFile.json and it works.  So I think my question is my blackbox_edit_start looking in the wrong root path?

I have tried deleting my repo and re-cloning I have also tried removing my user and re-adding.

**Comment by tlimoncelli** [comment]
The files listed in blackbox-files.txt need to be relative to the base of the git repo. (no ".." or etc.).  

I'm a bit stumped.   Can you post the command you run as well as all the output? (redacted as required)  maybe that will help.

Thanks!

**Comment by mdumouchel** [comment]
So it was a case issue.  I had cd into a drive with caps and when I would do the blackbox_edit_start it was using lowercase.  I just renamed the folder to be lower case.  Thanks for you help tlimoncelli.
