### ISSUE TITLE
create a `blackbox_list_admins` script

### ISSUE THREAD

**Issue by jvanasco** [StackExchange/blackbox#151]
I'll submit a PR for this later.

`blackbox_list_admins` simply shows the `cat /keyrings/live/blackbox-admins.txt`.

The reason for having this is that typing the command will work if the `cwd` is anywhere in a repo:

```
cat /path/to/repo/keyrings/live/blackbox-admins.txt
cat ../../../../../../../../../../../keyrings/live/blackbox-admins.txt
```

vs

```
blackbox_list_admins
```

**Comment by josegonzalez** [comment]
This can be closed as the pr was merged.
