### ISSUE TITLE
feature suggestion: `blackbox_update $FILENAME`

### ISSUE THREAD

**Issue by jvanasco** [StackExchange/blackbox#157]
is there a good reason why there isn't a `blackbox_update $FILENAME` and instead the `blackbox_update_all_files` ?

the use-case is that the `blackbox_edit*`workflow is rather constricting.

**Comment by tlimoncelli** [comment]
Good suggestion!

If you want to hack blackbox_update_all_files to create a blackbox_update script, I'd be glad to accept the PR.

**Comment by jvanasco** [comment]
will do!

**Comment by jvanasco** [comment]
on second thought, how do you feel about this:

* blackbox_encrypt_file $FILENAME
* blackbox_decrypt_file $FILENAME

**Comment by tlimoncelli** [comment]
blackbox_decrypt_file is blackbox_edit_start.  blackbox_encrypt_file is blackbox_edit_end.  I think the issue here is that these commands are badly named.  I have proposals for new names in https://github.com/StackExchange/blackbox/blob/master/Version2-Ideas.md

**Comment by jvanasco** [comment]
oh those names are way better.  I'll close this ticket.

The edit_start and edit_end suggested there was some workflow involved with a given file.
