### ISSUE TITLE
Support multiple environments

### ISSUE THREAD

**Issue by jabley** [StackExchange/blackbox#171]
I would like to have development, staging, and production environment credentials stored in my VCS.

The same people should not have access to all of those credentials.

- The development environment can potentially be unencrypted, or use one set of keys
- The staging and production env credentials should only be editable by those with production access (so a smaller, or even completely different, set of keys)

**Comment by tlimoncelli** [comment]
If the dev/stage/prod credentials are in different files, you can simply set $BLACKBOXDATA to the appropriate directory. The default is keyrings/live.  Each directory can have a different list of files that are encrypted, different admins, etc.

If the same file should contain different values for dev/stage/prod, then Blackbox doesn't support your situation.  You could put they values in different places and write a script that installs them to the right place.

Feel free to re-open this issue if you have further questions. If you are interested in adding such features to bb, that'd be awesome too!
