### ISSUE TITLE
blackbox_postdeploy question

### ISSUE THREAD

**Issue by KateWilkins** [StackExchange/blackbox#174]
is there a way to control/force which admin postdeploy will use. We have 4 admins setup and when our main deploy script runs (as root) it invokes blackbox_postdeploy but it always asks for a particular admin password first (quite slow/inconvenient).

We'd like to automate so that we can force which admin into blackbox_postdeply will ask the password for.

Thanks
Kate

**Comment by tlimoncelli** [comment]
I'm not a GPG expert but try checking the man page. There may be a way to select a default (maybe set an env variable?)

**Comment by tlimoncelli** [comment]
Culling old issues. Please re-open if this is still an issue.
