### ISSUE TITLE
Cmder integration

### ISSUE THREAD

**Issue by jrappen** [StackExchange/blackbox#176]
How do I use [`blackbox`](https://github.com/StackExchange/blackbox) with [cmder](https://github.com/cmderdev/cmder) (consule emulator for Windows)?

---

### What I tried...

* Copied files from this repo to `cmder/vendor/blackbox` subfolder.
* Added line `set PATH=%CMDER_ROOT%\vendor\blackbox\bin;%PATH%` to file `cmder/config/user-profile.cmd`

#### `cmd`

```text
λ sh blackbox_initialize
%CMDER_ROOT%/vendor/blackbox/bin/blackbox_initialize: line 12: blackbox_initialize/_blackbox_common.sh: No such file or directory
```

#### `bash`

```text
$ blackbox_initialize
bash: blackbox_initialize: command not found
```

#### `mintty`

```text
$ blackbox_initialize
bash: blackbox_initialize: command not found
```

**Comment by tlimoncelli** [comment]
Make sure that %CMDER_ROOT%/vendor/blackbox/bin is in your PATH.

**Comment by jrappen** [comment]
@tlimoncelli As stated above, that didn't work for me.

**Comment by jrappen** [comment]
@cmderdev Any suggestions?

**Comment by tlimoncelli** [comment]
Sadly I've never tested blackbox on the new Bash for Windows system. I would check things like whether or not the files are marked as executable, and if the "#!" line at the top of each file lists a valid path.

I'd definitely like BB to work on Windows.  If you figure out how to get it working, I'd appreciate a write-up that can be put on the wiki.

**Comment by jrappen** [comment]
@tlimoncelli [Cmder](https://github.com/cmderdev/cmder) is a wrapper around [ConEmu](https://github.com/maximus5/conemu). My issue is not related to Bash on Windows.

**Comment by tlimoncelli** [comment]
Does it work under cmd.exe but not ConEmu?

**Comment by jrappen** [comment]
@tlimoncelli no

**Comment by Maximus5** [comment]
Topic started didn't mention "Bash for Windows". But "standard" mintty was mentioned. That's either cygwin or msys.

**Comment by tlimoncelli** [comment]
@mhenderson-so can you take a look?

**Comment by mhenderson-so** [comment]
@jrappen I can't find any documentation around how cmder's `vendor` folder works at all, or how it's meant to be used, or how it gets invoked, or anything. Are you able to point me to some documentation so I can look at this further?

**Comment by Maximus5** [comment]
I believe the behavior is the same if you run `sh blackbox_initialize` from standard `cmd.exe`. Using same PATH and msys version.

The vendor folder is just a location for portable software. The `PATH` initialization matters only.

**Comment by jrappen** [comment]
@mhenderson-so I documented what I did in my first post at the top of the page.

**Comment by jrappen** [comment]
@mhenderson-so Any updates?

**Comment by mhenderson-so** [comment]
@jrappen I'm still not sure I understand exactly what you've done. I'm not an expert in cmder, or ConEmu unfortunately.

However, BlackBox is not portable software. It is a collection of Bash scripts that in turn executes other tools like gpg, shred, diff, etc. It needs a proper *nix system underneath it to work.

I'm not sure you're going to be able to do what you're trying to do.

**Comment by jrappen** [comment]
@mhenderson-so Ok, thank you for looking into this.
