### ISSUE TITLE
Using postdeploy with a subkey

### ISSUE THREAD

**Issue by jeancochrane** [StackExchange/blackbox#178]
Hey all,

Thanks for the great work on blackbox. I love being able to keep my secrets under version control!

I'm having trouble setting up an automated postdeploy to run properly with a subkey. My server is running Ubuntu 16.04, and my local machine is running OS X El Capitan. I'm new to sysadmin stuff, so it's likely that this involves a beginner mistake.

I followed [your guide in the docs](https://github.com/StackExchange/blackbox#set-up-automated-users-or-role-accounts) and everything went smoothly in terms of generating/importing the key, but now I can't seem to get my server to use the subkey instead of prompting me for a password. When my git hook runs, it prints out key import behavior that looks good:

```
========== Importing keychain: START
gpg: Total number processed: 2
gpg:              unchanged: 2
========== Importing keychain: DONE
========== Decrypting new/changed files: START
```

 But then it prints this mysterious error message:

```
gpg: cannot open tty '/dev/tty': No such device or address
```

Weird. When I manually run `blackbox_postdeploy` on the server, I get prompted for a password:

```
You need a passphrase to unlock the secret key for
user: "Deploy Key <[dummy address]>"
4096-bit RSA key, ID 876C2718, created 2016-12-30 (main key ID FC7DCF2C)

gpg: gpg-agent is not available in this session
Enter passphrase:
```

This seems odd, because the key requiring a passphrase (ID 876C2718) is the subkey I generated with no passphrase, listed second when I run `gpg --list-keys`:

```
pub   4096R/FC7DCF2C 2016-12-30
uid                  Deploy Key <[dummy address]>
sub   4096R/FA951FBA 2016-12-30
sub   4096R/876C2718 2016-12-30
```

Any idea what could be going on here? Have you seen similar issues before? All I can think of is that I must have accidentally generated the subkey with a password, although I'm not sure how I can check that (and I very much don't remember using a password). Any/all thoughts appreciated!

**Comment by tlimoncelli** [comment]
Hi Jean!

I'm glad you find blackbox useful.

I'm going to guess that it is one of two things (a) The subkey does have a passphrase (as you surmised), (b) gpg doesn't know to use the subkey and is trying to use the primary key.

See if you can gpg decrypt a file using the gpg commands.  If that doesn't work, the subkey was made incorrectly. If that does work, then we know the problem is in the script.

Tom

**Comment by jeancochrane** [comment]
Thanks for getting back to me, Tom! I tried using the gpg utility and it identified the right subkey, but still asked for a password. I must have generated the subkey incorrectly. 

I'm going to try making the subkey again – I'll let you know how it goes. Thanks again for the help!

**Comment by jeancochrane** [comment]
Turns out I had forgotten to do the very last step of setting up a subkey (selecting the new key and removing the password). Oops... Deploy hook is working beautifully now.

Thanks for all your help, @tlimoncelli!
