### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by matthughes** [StackExchange/blackbox#181]
I see there was a new release in January, but I can't seem to find release notes / changelog anywhere.  Could you either point me in the right direction or add a mechanism to track changes?  I'd be happy with a simple CHANGELOG.md at the root of the project; that seems to suffice for many projects.

**Comment by tlimoncelli** [comment]
Yeah, I guess I should maintain a CHANGELOG.  I've been kind of slack about that kind of thing.

Can you recommend a format for the CHANGELOG.md?  is there another project we could emulate?

**Comment by matthughes** [comment]
Seems that lots of projects are just doing simple markdown based format:

* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md
* https://github.com/docker/docker/blob/master/CHANGELOG.md

**Comment by tlimoncelli** [comment]
Done.  (Hopefully I'll remember to update CHANGELOG.md :-) )
