### ISSUE TITLE
make confidence with errors

### ISSUE THREAD

**Issue by painhardcore** [StackExchange/blackbox#183]
I was trying to make a PR with another issue, but can't - "make confidence" shows some errors
First when git config command enters without git repository it's fatal error "not in git repository"
[Here easy fix](https://github.com/painhardcore/blackbox/commit/98b928c0e80e2d1911f2db5a558cd5b93375f1da)
But then I got an error at the end when "blackbox_shred_all_files" is executed and somehow skip's the "space space.txt"

i've printed ls of directory and content of keyrings/live/blackbox-files.txt before blackbox_shred_all_files

```bash
********************
********************
********* Bob shreds all exposed files.
********************
********************
total 80
-rw-r--r--    1 kotey  staff   362 19 фев 22:33 !important!.txt.gpg
-rw-r--r--    1 kotey  staff   368 19 фев 22:33 #andpounds.txt.gpg
drwx------   15 kotey  staff   510 19 фев 22:33 .
drwx------  187 kotey  staff  6358 19 фев 22:33 ..
drwxr-xr-x   13 kotey  staff   442 19 фев 22:33 .git
-rw-r--r--    1 kotey  staff   204 19 фев 22:33 .gitignore
drwxr-xr-x    3 kotey  staff   102 19 фев 22:33 keyrings
-rw-r--r--    1 kotey  staff   368 19 фев 22:33 mistake.txt.gpg
drwxr-xr-x    3 kotey  staff   102 19 фев 22:33 my
-rw-r--r--    1 kotey  staff    16 19 фев 22:33 secret.txt
-rw-r--r--    1 kotey  staff   349 19 фев 22:33 secret.txt.gpg
-rw-r--r--    1 kotey  staff    19 19 фев 22:33 space space.txt
-rw-r--r--    1 kotey  staff   359 19 фев 22:33 space space.txt.gpg
-rw-r--r--    1 kotey  staff    32 19 фев 22:33 stars*bars?.txt
-rw-r--r--    1 kotey  staff   378 19 фев 22:33 stars*bars?.txt.gpg
!important!.txt
#andpounds.txt
mistake.txt
my/path/to/relsecrets.txt
secret.txt
space space.txt
stars*bars?.txt
========== FILES BEING SHREDDED:
    secret.txt
    my/path/to/relsecrets.txt
    stars*bars?.txt
shred_file: WARNING: No secure deletion utility (shred or srm) present; using insecure rm
shred_file: WARNING: No secure deletion utility (shred or srm) present; using insecure rm
shred_file: WARNING: No secure deletion utility (shred or srm) present; using insecure rm
========== DONE.
ASSERT FAILED: space space.txt should not exist.
``` 

Not sure what gone wrong and how to fix that.
MAC OS 10.12.3

**Comment by tlimoncelli** [comment]
I make the change you suggested (thanks!).  Sadly I can't get "make confidence" working on macOS 10.12.2 working because I upgraded GnuPG which seems to have broken it.  Meanwhile 

Meanwhile I can't get it working on Linux (CENTOS 7) (batch creation of keys spins forever).

I committed some fixes but I don't have time to work on this today. Maybe that's enough for you to continue.

**Comment by painhardcore** [comment]
@tlimoncelli I've tried repository with last commit with latest ubuntu and centos clean install but it breaks at different places.

**Comment by tlimoncelli** [comment]
Sorry I dropped the ball on this. Would you please check to see if the changes I've made in the last few months covered this situation? If not, please rebase and I'll take a look at the PR again.
