### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by josegonzalez** [StackExchange/blackbox#186]
They currently seem to be run manually. I haven't had a chance to take a stab at this, but do you have a preferred public CI toolchain that you'd like me to use?

**Comment by tlimoncelli** [comment]
I don't have a preference.  I know that Jenkins is popular with open source packages but I'm open to anything.

**Comment by josegonzalez** [comment]
Well something like travis or circleci is what I meant.

**Comment by tlimoncelli** [comment]
Either travis or circleci is great.  I have a slight preference for travis.

**Comment by josegonzalez** [comment]
Any idea why it might be hanging here/what I can do to fix the hangs? https://travis-ci.org/josegonzalez/blackbox/builds/213205514

**Comment by josegonzalez** [comment]
Sure. Will the passphrase be the same each time?

**Comment by tlimoncelli** [comment]
The password will either be "a" or "b" (yes, just 1 letter, lower case). There will be text that says what it will be shortly before the prompt.

If I remember the "expect" language, you could set a variable to "a" any time you see the text "lowercase letter a" and "b" any time you see the text "lowercase letter b".  Then any time you see the prompt, send what is in that letter.

Or, just remember that the first 3 prompts are "a", the next three are "b". (I think it is 3 and 3.  Not 100% sure).

Tom

**Comment by tlimoncelli** [comment]
FYI: "make test" is no longer interactive (i.e. it no longer pauses to ask for passwords, etc.)

It should be pretty easy to set up CI now.

I recommend it do:

    make test
    make packages-rpm
    make packages-deb

If you are still willing to volunteer to set that up, I'd be forever grateful.

**Comment by josegonzalez** [comment]
Closer, but the gpg-agent definitely asks for a password: https://travis-ci.org/josegonzalez/blackbox/builds/237347010

I'm not too familiar with `expect`, any chance you have a moment to dig at that?

**Comment by tlimoncelli** [comment]
Is `gpg-agent` in the PATH?   It may be in a separate package depending on the distro.

Line 273-274:

    tools/confidence_test.sh: line 27: gpg-agent: command not found
    tools/confidence_test.sh: line 33: gpg-agent: command not found

Line 429:

    gpg: gpg-agent is not available in this session

**Comment by josegonzalez** [comment]
I added `gnupg-agent` as an installable package, but that didn't seem to help :|

**Comment by tlimoncelli** [comment]
It looks like that did help.  The new error is due to pinentry-tty and pinentry not being found.

Hmm... maybe that script should first check to make sure all the tools it needs are found.

Tom

**Comment by tlimoncelli** [comment]
I just committed 7c4fa4f4bed91a1324b95001fb7cb9c646fc1291 which does an explicit test to make sure that pinentry, gpg-agent, and other programs are in the $PATH.  This should help with that situation, plus prevent future problems. Also, people running the tests in their own environment will find fewer surprises.
