### ISSUE TITLE
Blackbox don't work with version 2.1 and above of gpg-agent

### ISSUE THREAD

**Issue by smgt** [StackExchange/blackbox#188]
Error: I can't run `blackbox_update_all_files` since it requires the environment variable `GPG_AGENT_INFO` to be set by `gpg-agent`.

Version 2.1.11 of `gpg-agent` don't set `$GPG_AGENT_INFO` and you can't invoke the daemon and set the environment variable with `eval $(gpg-agent --daemon)`. The socket ends up in `$HOME/.gnupg/S.gpg-agent`.

The recommendation from `gpg-agent` 2.1.11 is not to manually start it but let `gpg` handle the invocation.

What version of `gpg-agent` do you recommend?

From https://www.gnupg.org/faq/whats-new-in-2.1.html

> The gpg-agent is the central part of the GnuPG system. It takes care of all private (secret) keys and if required diverts operations to a smartcard or other token. It also provides support for the Secure Shell by implementing the ssh-agent protocol.

> The classic way to run gpg-agent on Unix systems is by launching it at login time and use an environment variable (GPG_AGENT_INFO) to tell the other GnuPG modules how to connect to the agent. However, correctly managing the start up and this environment variable is cumbersome so that that an easier method is required. Since GnuPG 2.0.16 the --use-standard-socket option already allowed to start the agent on the fly; however the environment variable was still required.

> With GnuPG 2.1 the need of GPG_AGENT_INFO has been completely removed and the variable is ignored. Instead a fixed Unix domain socket named S.gpg-agent in the GnuPG home directory (by default ~/.gnupg) is used. The agent is also started on demand by all tools requiring services from the agent.

A temporary solution is to just run `export GPG_AGENT_INFO=fun`.

**Comment by tlimoncelli** [comment]
There are 4 programs that try to be helpful this way:

- `blackbox_decrypt_all_files`
- `blackbox_diff`
- `blackbox_update_all_files`
- `blackbox_whatsnew`

Each of them need some kind of "if gpg-agent 2.1 or higher is in use, don't muck with `GPG_AGENT_INFO` code.

I think a valid test would be:

    gpg-agent --version | head -1 | grep -s ' 2.0' ; echo $?

as in:

   if gpg-agent --version | head -1 | grep -s ' 2.0' ; then echo OLD SCHOOL ; else echo GPG 2.1 or higher ; fi

Would you consider submitting a PR?

**Comment by smgt** [comment]
Yes, I will take a look at it.
