### ISSUE TITLE
Handling hierarchical access

### ISSUE THREAD

**Issue by mlosapio** [StackExchange/blackbox#190]
**Feature request / design doc**
concept/implementation of group-based hierarchical access

**Rough design thoughts**
*(A Simple model)* 

- Files get assigned to groups.
- There is a 1:many relationship between files and groups.
- Users get assigned to groups.
- There is a 1:many relationship with users and groups.

- The default-posture would be 1 file-group and 1 user-group. 
 

Thoughts?

**Comment by tlimoncelli** [comment]
I appreciate your enthusiasm.  However I'd back up a bit and first work out some requirements. What problem are you trying to solve?  What typical use-cases do you want to satisfy?

When you say "group-based hierarchical access" could you clarify what you mean by that?

**Comment by mlosapio** [comment]
Sure, the problem we're trying to solve is classifying groups of files with different security/access levels - bucketing users into those levels and matching access to those levels. 

Example: 
user1 (lower trust)
user2 (lower trust)
admin1 (higher trust)
admin2 (higher trust)

Files needed to be secured:
file1 file2 file3 file4

Use case:
user1 and user2 gets access to file1 and file2
admin1 and admin2 gets access to file1 file2 file3 file4

Encrypting puppet hiera files would be one example where we're seeing this need...

**Comment by tlimoncelli** [comment]
That's a much better start. Thanks!

Yes, I can see the need for this kind of thing. Currently you can set different keyrings and encrypt each file with a different one. You have to manually make sure no file is listed in more than one keyrings/*/blackbox-files.txt files. So, I see this as a layer that would manage the existing system easier.

There needs to be operations that would add/change/delete groups, users in groups, assign files to groups, etc.  What do you propose?

**Comment by tachang** [comment]
I could imagine using this if a new intern comes on board and you don't want to give them the production credentials right away for fear they might blow something away:

https://www.reddit.com/r/cscareerquestions/comments/6ez8ag/accidentally_destroyed_production_database_on/

**Comment by Cinderhaze** [comment]
I know that in the context of hiera, there is a hiera-eyaml-gpg gem that allows you to use a ring of trust, and the way that it works under the covers is that it encrypts the data with a one time pad, and every user who is added to the keyring gets the one time pad encrypted with their cert.  

I come at this knowing nothing about how this project works under the hood, but you could do something similar with 'groups', the group's files would use a group specific one time pad, and then the user's key would decrypt the group one time pad to use for the file decryption.

**Comment by torkelrogstad** [comment]
> Currently you can set different keyrings and encrypt each file with a different one. You have to manually make sure no file is listed in more than one keyrings/*/blackbox-files.txt files. 

Are there any documentation on how to do this?

**Comment by tlimoncelli** [comment]
Not currently. The env variable BLACKBOXDATA overrides the directory.

**Comment by tlimoncelli** [comment]
I've decided to close this feature request as this is not something that Blackbox is going to do. Having a single file that could be decrypted by more than one key ring is not a feature we plan on doing. 

We'd like to keep blackbox simple. It is a bash wrapper around GPG and nothing more. We are pushing the limits of what can be reasonably done in Bash and the code is starting to get brittle and untestable.

If we get into hierarchical access suddenly we have a lot of new questions to answer: how should blackbox_decrypt_all_files work?  How do we ban one user if they have permission from another keyring?  etc. etc.

If you need hierarchical access, I highly recommend considering git-crypt, Vault, and other fine products.  I don't see Blackbox expanding in this area in the future.
