### ISSUE TITLE
Can't manage to make blackbox work on Cygwin

### ISSUE THREAD

**Issue by Zephir77167** [StackExchange/blackbox#195]
Hi,

I recently cloned blackbox, then copied all files from `bin` to `/usr/bin`.

When I try to run `blackbox_edit_start x` for an example, I get:

`/bin/bash: /usr/bin/blackbox_edit_start: No such file or directory`

Same for `/usr/bin/blackbox_edit_start x`. And when I run `stat /usr/bin/blackbox_edit_start`:

```
File: /usr/bin/blackbox_edit_start
  Size: 919             Blocks: 4          IO Block: 65536  regular file
Device: 671faeah/108133098d     Inode: 2533274790752086  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (197609/   adrie)   Gid: (197609/   adrie)
Access: 2017-06-07 17:09:44.425527200 +0200
Modify: 2017-06-07 17:09:44.429570800 +0200
Change: 2017-06-07 17:37:15.930554900 +0200
 Birth: 2017-06-07 15:34:50.354512200 +0200
```

What am I missing here?

PS: I tried to chmod it, in vain.

Thanks in advance!

Edit: when I try to run the scripts from bin without putting them in `/usr/bin`:
```
./blackbox_edit_start: ligne 2: $'\r' : command not found
./blackbox_edit_start: ligne 6: $'\r' : command not found : option non valable: ligne 7 : set: - set : utilisation : set [-abefhkmnptuvxBCHP] [-o nom-option] [--] [arg ...] : no such file or directory: blackbox_common.sh
./blackbox_edit_start: ligne 9: $'\r' : command not found
./blackbox_edit_start: ligne 15: syntax errr near symbol « $'do\r' » '
./blackbox_edit_start: ligne 15: `for param in "$@" ; do
```

**Comment by tlimoncelli** [comment]
what operating system are you using?

**Comment by tlimoncelli** [comment]
It looks like the line endings on the files should be unix style (\n) not windows style (\r\n).  Please make sure that git checkout is not modifying the files.

CC: @bendra

**Comment by Zephir77167** [comment]
Hi,

I am using Windows 10 64 bits.

Indeed, git had replaced all `\n` with `\r\n`... I replaced them again to match the unix-style, and now I can run the scripts using `./blackbox_xxx` in `/usr/bin`, but still can't execute them from anywhere using `blackbox_xxx` (still with the same error `No such file or directory`). It works for every other file in `/usr/bin` though, it is very weird. As I need to execute them in other scripts, I am a bit stuck by this error...

**Comment by tlimoncelli** [comment]
It sounds like a permissions problem Try: "chmod 0755 blackbox_xxx"

**Comment by Zephir77167** [comment]
Nevermind, it was a more obscure problem. To make it short, instead of running bash scripts with `/usr/bin/bash.exe`, cygwin was resolving `C:\Windows\System32\bash.exe` first (Ubuntu's bash).

Thanks anyways for your help!
