### ISSUE TITLE
Decrypted filenames end with carriage return on Windows

### ISSUE THREAD

**Issue by akwizgran** [StackExchange/blackbox#197]
If the file containing the names of files managed by blackbox has DOS line endings (CRLF), the names of the decrypted files created by commands such as `blackbox_decrypt_all_files` end with carriage returns. This can happen, for example, when checking out a Git repo on a Windows machine with `core.autocrlf = true`, which is the recommended setting on Windows.

The issue can be fixed by consuming the carriage return when looping over the lines of the file. Instead of using `while IFS= read`, blackbox should use `while IFS=$'\r' read`. This works with either DOS or Unix line endings.

**Comment by tlimoncelli** [comment]
Is there a way to tell Git to not change the line endings on a specific file?

**Comment by akwizgran** [comment]
> Is there a way to tell Git to not change the line endings on a specific file?

Good point! StackOverflow says [yes](https://stackoverflow.com/questions/19551037/git-how-to-keep-crlf-endings-for-specific-files-only). I guess Blackbox could add this to the Git config? It seems to me that the bug would still exist with other version control systems though, if blackbox-files.txt was either created on a Windows system or checked out with a VCS that converts line endings, like Git.

**Comment by tlimoncelli** [comment]
Rather than handling CRLF better, I've made Blackbox do the right things so that no conversion happens.

blackbox_initialize now creates the proper .gitattributes file if Git is in use.  Legacy repos will have to follow the instructions in README.md, which now spell out what needs to be done.

Thanks for raising this issue!
