### ISSUE TITLE
Discover an alternative vault path

### ISSUE THREAD

**Issue by aymericbeaumet** [StackExchange/blackbox#201]
Right now blackbox will look for `./keyrings/live` in the root folder to perform the decryption. I think we should also allow for the alternative path: `.blackbox` (dropping the `live` part).

Reasons:
- Blackbox is an auxiliary tool, and IMO should be present as a hidden file (i.e.: not the same level as the real source files)
- The name would be more explicitly linked to this tool, `keyrings` is too generic

This change can be made in a backward compatible way by ensuring `./keyrings/live` is always loaded first if present.

I'm pretty sure I've seen a comment about this on this repo, but I can't find it anymore.

**Comment by aymericbeaumet** [comment]
@tlimoncelli Would you be willing to receive a PR for this?

**Comment by tlimoncelli** [comment]
Absolutely!  We love PRs!

To make it easier to submit PRs, we've included a "make test" that verifies basic functionality.  If "make test" works, at last you know you haven't broken any legacy features. Feel free to add more tests to tools/confidence_test.sh as part of your PR.  Caveat: the tests require "expect" and "pinentry-tty" to be installed.
