### ISSUE TITLE
Incorrect chmod use on Alpine Linux

### ISSUE THREAD

**Issue by jagregory** [StackExchange/blackbox#211]
Alpine Linux's `chmod` doesn't have the `--reference` parameter, so postdeploy fails in `cp_permissions` with the following error:

`chmod: unrecognized option: reference`

I'm no expert on Alpine, but we use it for it's small footprint in Docker. As we're using Concourse CI, all our builds run in containers and ideally, Alpine.

From what I can see, `uname` reports `Linux` on Alpine, but the `chmod` command doesn't support `--reference`; additionally, the `stat` command also behaves slightly differently, so it's not just a case of using the same approach as FreeBSD/Darwin.

I have a working version by patching `cp_permissions` to run:

`chmod $( stat -c '%a' "$1" ) "${@:2}"`

However, I don't know how to modify the `uname` check to cater for this. I suppose there either needs to be a more sophisticated OS check or a capabilities check of chmod (like grepping `chmod --help` or something).

**Comment by tlimoncelli** [comment]
Googling [how to tell if i'm running alpine linux] finds https://superuser.com/questions/148902/how-do-i-check-alpines-version which isn't exactly the same thing. That said, I think that it is safe to assume that we are running Alpine if `/etc/alpine-release` exists.

Does that help?

**Comment by jagregory** [comment]
Ok, that sounds promising. It looks like a test for an `alpine` executable is another possibility.

How would you feel about the following change?

```sh
function cp_permissions() {
  # Copy the perms of $1 onto $2 .. end.
  case $(uname -s) in
    Darwin )
      chmod $( stat -f '%p' "$1" ) "${@:2}"
      ;;
    FreeBSD )
      chmod $( stat -f '%p' "$1" | sed -e "s/^100//" ) "${@:2}"
      ;;
    Linux | CYGWIN* | MINGW* )
      if [[ -e /etc/alpine-release ]]; then
        chmod $( stat -c '%a' "$1" ) "${@:2}"
      else
        chmod --reference "$1" "${@:2}"
      fi
      ;;
    * )
      echo 'ERROR: Unknown OS. Exiting. (cp_permissions)'
      exit 1
      ;;
  esac
}
```

**Comment by tlimoncelli** [comment]
Looks good!  Would you please make a PR?

**Comment by jagregory** [comment]
Here you go: https://github.com/StackExchange/blackbox/pull/212

I had some trouble running the full test suite on Alpine, something to do with the GPG agent, but I can confirm the permissions specific tests did originally fail and now pass with this PR.

**Comment by jagregory** [comment]
Closing because #212 was merged.
