### ISSUE TITLE
Configuration for bare repositories

### ISSUE THREAD

**Issue by Libbum** [StackExchange/blackbox#217]
If you configure a dotfiles repository using a bare repo and set up the working tree to be your home directory (via [this guide](https://legacy-developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/) for example), running `blackbox_initialize` will fail.

The home directory yields the obvious `Not in a known VCS directory`, and the repo directory an expected `fatal: This operation must be run in a work tree`.

Is there a way to correctly initialise this kind of configuration?

**Comment by TomOnTime** [comment]
Yes, I can imagine the VCS finder breaks when run in $HOME. That
wasn't something I tested.

In the meanwhile, I would run blackbox_initialize in a subdirectory
then rename things down to the parent,  It should work.

Tom

**Comment by Libbum** [comment]
Can confirm. One also needs to run `blackbox_addadmin` in this manner also otherwise things wont work. Thanks.
