### ISSUE TITLE
gpg: key export failed: invalid packet

### ISSUE THREAD

**Issue by jeancochrane** [StackExchange/blackbox#240]
I'm running Ubuntu 16.04 with both `gpg` and `gpg2` installed. When I run blackbox with no arguments, I get an esoteric error message complaining about packets:

```
blackbox_cat configs/secretfile.conf.gpg 
========== PLAINFILE "configs/secretfile.conf"
========== Importing keychain: START
gpg: [don't know]: invalid packet (ctb=00)
gpg: key export failed: invalid packet
```

When I tell blackbox to use `gpg2`, however, everything works like a dream:

```
GPG=gpg2 blackbox_cat configs/secretfile.conf.gpg 
========== PLAINFILE "configs/secretfile.conf"
========== Importing keychain: START
gpg: Total number processed: 76
gpg:              unchanged: 76
========== Importing keychain: DONE
========== EXTRACTING configs/secretfile.conf
(... file prints here ...)
```

Seems like something's up with `gpg` 1.0 here. Decrypting the file directly is fine, however:

```
gpg -d configs/secretfile.conf.gpg

You need a passphrase to unlock the secret key for
user: "My Name <myemail@test.com>"
4096-bit RSA key, ID 99999999, created 2000-01-01 (main key ID 99999999)

(... file prints here ...)
```

My `gpg` versions:

```
gpg --version
gpg (GnuPG) 1.4.20

gpg2 --version
gpg (GnuPG) 2.1.11
libgcrypt 1.6.5
```

Any thoughts on where I should look to start debugging this? I'm in an internet rabbit hole trying to figure out what's up with packets.

Consider this very low priority; I'm just going to export the `GPG` variable on login and roll with `gpg2` from here on out. Mostly filing this out of curiosity, and to help anyone else who may be searching for the same error message.

**Comment by tlimoncelli** [comment]
Yeah, it is kind of difficult to support old GPG versions and I must confess that my motivation is low too.  if gpg2 works for you, I'd stick with it. 

Maybe we  should sunset gpg1 support.

**Comment by jeancochrane** [comment]
Thanks for the prompt response @tlimoncelli! My apologies for not getting back to you sooner.

Agreed, gpg versioning is a major headache all around. I'll stick with gpg2 for now since it seems to be working fine. Sunsetting gpg1 is an interesting idea, but seems bigger than this particular issue. Pending any more concrete next steps, I'll close this for now.
