### ISSUE TITLE
manual install directions are bad

### ISSUE THREAD

**Issue by jvanasco** [StackExchange/blackbox#243]
The docs state this:

> The manual way: make manual-install to install. make manual-uninstall to uninstall.

That doesn't really 'install'.  It symlinks the download/directory into `/usr/local/bin`.  If that directory gets erased, it blackbox does too.

This behavior could use a warning.  The local download got cleared off a server during a change in deployment systems, and effectively broke everything.

**Comment by tlimoncelli** [comment]
Thank you for pointing that out.

I've clarified and cleaned up the code in https://github.com/StackExchange/blackbox/pull/244

**Comment by jvanasco** [comment]
looks great, thanks!
