### ISSUE TITLE
Upgrade CircleCI config to 2.0 format

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/blackbox#245]
1.0 files are going to be disabled soon. We need to convert.
https://circleci.com/sunset1-0/

Volunteer?

**Comment by aymericbeaumet** [comment]
We should be fine as we are already leveraging the [version 2](https://github.com/StackExchange/blackbox/blob/master/.circleci/config.yml#L1) of their API 👍

**Comment by tlimoncelli** [comment]
awesome!
