### ISSUE TITLE
alias commands / renaming ?

### ISSUE THREAD

**Issue by jvanasco** [StackExchange/blackbox#253]
I just wanted to suggest renaming/aliasing a few commands:

* `blackbox_register_new_file ` -> `blackbox_enroll`
* `blackbox_edit_start ` -> `blackbox_decrypt`
* `blackbox_edit_end ` -> `blackbox_encrypt`

i'm basing the suggestions not only on what I often think about (and search for when I forget!) but that's what blackbox uses in the docs for each command, asking "how do i ___?"

**Comment by tlimoncelli** [comment]
Thanks for the feedback.  We've been thinking about this for a 2.0 release: https://github.com/StackExchange/blackbox/blob/master/Version2-Ideas.md 
What are your thoughts?

**Comment by jvanasco** [comment]
ha! perfect!
