### ISSUE TITLE
tracking file changes via fingerprint/digest

### ISSUE THREAD

**Issue by jvanasco** [StackExchange/blackbox#254]
I suggest tracking the md5 (or other digest) of the plaintext decrypted file in the keyrings directory, and using a command such as `blackbox_staged` to see what files have staged changes.

why?

this would allow for edits to be determined without having to use `blackbox_diff` (which really requires the gpg agent to be running).  More importantly, this would also give accountability and tracking in the versioning system as to when files actually changed.  Since the tracked files are gpg encoded, a change can happen because the contents changed or keysigning changed.  Tracking/updating an md5 of the decrypted value would allow for actual changes to be "tracked". The version control would not know what inside the file changed, simply that the file actually changed.

**Comment by tlimoncelli** [comment]
Good suggestion. We've been thinking about doing that. It would be a bit difficult to do in bash, but we're thinking of rewriting things in Go.

**Comment by jvanasco** [comment]
Glad it's on the radar!

Are you sure about Go?

I recently had to install acme-dns (written in Go) for automating wildcard certificates with LetsEncrypt. I thought I could just install Go, but no – the max ubuntu version was far too old.  I had to configure new package sources, update, then install.  Finally it worked.  It was a headache.

**Comment by tlimoncelli** [comment]
Yes, go.  I'm sorry to hear that you had a problem with compiler versions on Ubuntu.

Pre-compiled binaries would be available in the "releases" area on Github.
