### ISSUE TITLE
The directions reference a ".blackbox" directory, which doesn't exist.

### ISSUE THREAD

**Issue by jvs** [StackExchange/blackbox#256]
To reproduce this issue:
```bash
mkdir newrepo
cd newrepo
git init
blackbox_initialize
gpg --homedir=.blackbox --list-keys
```

gpg will fail with "No such file or directory".

Notice that step 2 in the section "How to indoctrinate a new user into the system?" tells users to run `gpg --homedir=.blackbox --list-keys`. This won't work, along with many other commands in the README. (Or at least they don't seem to work for me, for some reason.)

I assume for git repos, `.blackbox` is actually `keyrings/live`? If this is the case, then the README needs to be updated.

**Comment by TomOnTime** [comment]
Older repos use keyrings/live instead of .blackbox. The code works with either.

I'll fix that in https://github.com/StackExchange/blackbox/pull/257
