### ISSUE TITLE
make packages-deb builds old 1.0 version instead of 1.2

### ISSUE THREAD

**Issue by dansou901** [StackExchange/blackbox#262]
When using make packages-deb on an Ubuntu 16.04 machine with fpm 1.10.2 installed, it builds version 1.0_462 with the current sources. Am I missing something or does something need to be updated in the source code?

**Comment by tlimoncelli** [comment]
Set the env variable $PKGRELEASE to whatever you want the release to be.  At Stack, we set it to the number in TeamCity (the CI system we use). Since the build number is always increasing, we are guaranteed to always have a reasonable release number.
