### ISSUE TITLE
feature request: Decrypt single file

### ISSUE THREAD

**Issue by tobdub** [StackExchange/blackbox#268]
Add a _blackbox_decrypt_file_ command to decrypt a single file.
I don't want to have to decrypt all files if I'm only interested in a single file.

**Comment by selfcommit** [comment]
Would that functionality be different from:
`blackbox_edit $filename` ?

**Comment by tobdub** [comment]
Yes, I don't want to edit the file. I just want to use it. For example to decrypt a private SSH key file and then use it.

**Comment by tlimoncelli** [comment]
that command is misnamed.  It is really "blackbox decrypt and leave the file there so it can be used, usually to edit but you can also just leave it there and use it".

**Comment by tobdub** [comment]
Looks like I can use `blackbox_edit_start $filename`. I was just worried that would leave some kind of state around if I don't call `blackbox_edit_end`.
Since there is a `blackbox_decrypt_all_files` I was expecting a `blackbox_decrypt_file` as well.

**Comment by tobdub** [comment]
I vote for adding an alias _blackbox_decrypt_file_ and/or updating the documentation with an example of decrypting a single file. Not having an obvious way to decrypt a single file could mean that some new users (like me) will use _decrypt_all_files_, which arguably is worse for security than only decrypting the needed file.

**Comment by tlimoncelli** [comment]
I agree. Would you like to submit a PR?  The file blackbox_decrypt_all_files is 90% similar.

**Comment by tobdub** [comment]
Sure, I'll prepare a PR.
