### ISSUE TITLE
Blackbox does not use .blackbox by default

### ISSUE THREAD

**Issue by kwilczek** [StackExchange/blackbox#269]
I read in the README that the `blackbox` should use `.blackbox` when creating a new repository. 
I cloned the the `master`, checked the logs to see if they include the release when this change was incorporated. Steps to reproduce:

`mkdir empty_repo && cd empty_repo && git init`
`blackbox_initialize`

As a result there is the `keyrings` directory and no `.blackbox` directory. 

From what I understand from the docs `keyrings/live` should no longer be used in modern versions of `Blackbox`. 

> Run the initialize script. This adds a few files to your repo in a directory called ".blackbox".

**Comment by tlimoncelli** [comment]
I can reproduce this bug.  Thanks for pointing it out!

**Comment by kwilczek** [comment]
I tracked the issue to these blocks:
- declaration on possible directories that contains both options

https://github.com/StackExchange/blackbox/blob/dc9fa326f468953d735d692dd42de74a16ee9163/bin/_blackbox_common.sh#L19-L23

- and the block that sets the `$BLACKBOXDATA` directory

https://github.com/StackExchange/blackbox/blob/dc9fa326f468953d735d692dd42de74a16ee9163/bin/_blackbox_common.sh#L73-L81

1. Is the first test (why mix `[` and `[[`?) needed? The first occurrence of the `$BLACKBOXDATA` is in this line (it is not present in the sourced `_stack_lib.sh`). I think it will always be `true` if someone will not explicitly set this variable.
2. The second line from the block sets the `$BLACKBOXDIR` to the first entry in the `$BLACKBOX_CANDIDATES` array, which is `keyrings/live`.
https://github.com/StackExchange/blackbox/blob/dc9fa326f468953d735d692dd42de74a16ee9163/bin/_blackbox_common.sh#L74
3. For new repositories this block will never set the `$BLACKBOXDATA`
https://github.com/StackExchange/blackbox/blob/dc9fa326f468953d735d692dd42de74a16ee9163/bin/_blackbox_common.sh#L75-L79
4. Which leaves us with `keyrings/live` for new repositories.

Will reversing the order of `$BLACKBOX_CANDIDATES` be enough?

**Comment by TomOnTime** [comment]
Yes. But also include a comment where BLACKBOXDATA_CANDIDATES is defined reminding people that the order matters and the default created directory is the last one.

**Comment by kwilczek** [comment]
I went with changing the order of the `BLACKBOX_CANDIDATES`. I feel that the `.blackbox` shouldn't be hardcoded in two places. If in future you decide that the dir should be named `.bbdir` ;) it would require changes in two places. I also added a comment to the array and created a PR.

**Comment by tlimoncelli** [comment]
Fixed in https://github.com/StackExchange/blackbox/pull/272
