### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by nikolay** [StackExchange/blackbox#285]
Is there a way to suppress the log spam from GPG?

**Comment by tlimoncelli** [comment]
Can you give an example?

**Comment by nikolay** [comment]
We have thousands of encrypted files. We have scripts that decrypt each of them to search for things inside, and only outputs messages when they find matches. Unfortunately, our tools' output is completely buried among the GPG tools' spam. You should provide a `--silent|-s` or `--quiet|-q` option, which silents GPG, and own output like most *nix tools. Here examples of the 'spam':

```
========== PLAINFILE "staging/aws-us-east-1/kernel-events/terraform.tfstate"
========== ENCRYPTED "staging/aws-us-east-1/kernel-events/terraform.tfstate.gpg"
========== Encrypting: staging/aws-us-east-1/kernel-events/terraform.tfstate
========== Encrypting: DONE
========== UPDATED "staging/aws-us-east-1/kernel-events/terraform.tfstate.gpg"
```

and

```
========== PLAINFILE "staging/aws-us-east-1/kernel-events/terraform.tfstate"
========== Importing keychain: START
gpg: Total number processed: 13
gpg:              unchanged: 13
========== Importing keychain: DONE
========== EXTRACTING staging/aws-us-east-1/kernel-events/terraform.tfstate
```

Multiply these by thousands and you get the picture.

**Comment by tlimoncelli** [comment]
Yeah, that's way more noisy than it needs to be.

(We'd gladly accept a PR.)

**Comment by TomOnTime** [comment]
FYI: v2 will be much less spammy.  One line per file, plus a the "importing keychain" only happens once.
