### ISSUE TITLE
Encrypt directory?

### ISSUE THREAD

**Issue by theoryshaw** [StackExchange/blackbox#289]
Is there a way to encrypt a directory, whereby any file you put in that directory will be automatically encrypted?

**Comment by tlimoncelli** [comment]
Welll.... I have some bad news :-(

That kind of thing is  intentionally not part of blackbox.

Blackbox is a bunch of shell scripts that prevent you from needing to remember GPG commands.  That's all.  If you are encrypting more than a few files (Or a few % of the files in a repo), I wouldn't trust it.  Other products will do a better job.

Best,
Tom

**Comment by theoryshaw** [comment]
Thanks!

😢
