### ISSUE TITLE
Document working with Ansible

### ISSUE THREAD

**Issue by oxr463** [StackExchange/blackbox#295]
I'd like to see more examples of this working with other configuration management tools besides Puppet.

**Comment by Keramblock** [comment]
Same here

**Comment by tlimoncelli** [comment]
I'd be glad to accept PRs.  I don't use Ansible so I can't really help much here. (Actually, I thought Ansible has its own mechanism for storing secrets... wouldn't that eliminate the need for Blackbox?)

**Comment by oxr463** [comment]
What you are referring to is `ansible-vault`; however, it still requires a master vault password file.

See: https://docs.ansible.com/ansible/latest/user_guide/vault.html#providing-vault-passwords

**Comment by TomOnTime** [comment]
Ah, yes, having a way to store the master vault password would be awesome.  Do you use blackbox for that?  Would you write brief few steps on how to set it up?
