### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by Ashwanth369** [StackExchange/blackbox#307]
Can you please give me a walkthrough of how install it on windows.

**Comment by tlimoncelli** [comment]
Blackbox is a number of Bash scripts, which is a Linux thing.  Getting it to run on Windows requires installing Cygwin or MinGW.  If you are familiar with those products, the tips on https://github.com/StackExchange/blackbox#using-blackbox-on-windows will help.

I'd like to rewrite the system using a language that works on Windows natively, such as Golang.  However that project is stalled.  Volunteers are needed to make that project go again.

There are alternatives that work on Windows.  Some are listed on https://github.com/StackExchange/blackbox#alternatives

Best,
Tom
