### ISSUE TITLE
Ist this Project Stale?

### ISSUE THREAD

**Issue by 6543** [StackExchange/blackbox#344]

**Comment by tlimoncelli** [comment]
It is in maintenance mode.  I'm not adding new features at this time; only fixing high severity bugs.

**Comment by 6543** [comment]
We at [Codeberg.org](https://codeberg.org) are currently using it and missing some features (`cat` & `edit`) and would like to ask if pull requests of that kind would be accepted or if we should fork this project?

**Comment by tlimoncelli** [comment]
I accept PRs.

**Comment by 6543** [comment]
I'll start working on it ...

Is it ok to delete the bash version at some point?

**Comment by tlimoncelli** [comment]
The bash version is the current version.  The Go version is an experiment that hasn't been announced (other than putting it in Git).  I don't think anyone uses it.  I'm not sure if the Go version is the right direction ... the code I wrote is more complex than I think it needs to be.

When (or if?) the Go version becomes stable, it should be replaced by the scripts in binv2 for backwards compatibility.  Those scripts are wrappers that call the new Go version.

If you would like to fork this project and work on the Go version, I would be delighted.  I don't have time to work on it any more.

Tom

**Comment by 6543** [comment]
also a focus is to have multible stores in one repo ... so you can have different teams but use the same gpg keystore etc ...

**Comment by TomOnTime** [comment]
Sounds good!
