### ISSUE TITLE
Errors after upgrading to OSX Monterey

### ISSUE THREAD

**Issue by dchi-sa** [StackExchange/blackbox#346]
We're getting `chmod: Invalid file mode: 100644` when running `blackbox_postdeploy` after upgrading OSX to Monterey?

**Comment by TomOnTime** [comment]
Hi!  Thanks for reporting this.  I haven't upgraded yet.

"chmod" is only run if "blackbox_postdeploy GROUP" is run, where "GROUP" is the name of a unix group.  I haven't tried this myself, but I'm going to guess that a workaround would be to leave off the GROUP.  That won't trigger the chmod that is giving the error.  You'll have to do your own chmod/chgrp.

Tom

**Comment by jsgv** [comment]
I have also experienced this. 

The issue is on the `cp_permissions` function in `blackbox_postdeploy`. 

`stat -f '%p' "$1"` gives groups and permissions.

`stat -f '%OLp' "$1"` gives permissions without the group.

https://github.com/StackExchange/blackbox/blob/master/bin/blackbox_postdeploy#L33
https://github.com/StackExchange/blackbox/blob/master/bin/_blackbox_common.sh#L435

**Comment by TomOnTime** [comment]
@jsgv Thanks for the analysis. Would you please submit a PR?

**Comment by jsgv** [comment]
Sure.

**Comment by TomOnTime** [comment]
Thanks, [jsgv](https://github.com/jsgv) for fixing this!  I don't have much time for blackbox any more and fixes like that are greatly appreciated!

**Comment by dchi-sa** [comment]
yup thanks so much @jsgv !  we tested it in our process and it works!

**Comment by jsgv** [comment]
Awesome! That is good to hear. Glad I could be of assistance. 😄

**Comment by Hititgirl** [comment]
Jajaja

**Comment by quentinsf** [comment]
Yup - appreciated here too.

**Comment by TomOnTime** [comment]
> This issue is still occurring for me on Monterey 12.4 (M1 Macbook) and Blackbox v2.0.0 as of today. I can open a new issue if that would be best.

Please try version v1.20220610  (the latest release).  v2.0.0 was an accidental tag.  We're still in our v1.x days.

Please reply with whether or not it works for you.

Tom
