### ISSUE TITLE
blackbox_postdeploy chmod: Invalid file mode: 100644

### ISSUE THREAD

**Issue by danielangelo** [StackExchange/blackbox#354]
When trying to run `blackbox_postdeploy ` or `blackbox_decrypt_all_files `  I get the following output:

```
========== Importing keychain: START
gpg: WARNING: nothing exported
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
========== Importing keychain: DONE
========== Decrypting new/changed files: START
========== EXTRACTED src/environments/environment.prod.ts
chmod: Invalid file mode: 100644
```

I am running this in a folder containing 2 encrypted files.

**Comment by tlimoncelli** [comment]
Did you recently upgrade your macos?  This sounds a lot like what was fixed in https://github.com/StackExchange/blackbox/pull/347

If you are running from "master", you should get that change.  I haven't scheduled a new release recently.

**Comment by danielangelo** [comment]
Hi @tlimoncelli . I have installed the version from homebrew. I will get the it from master. Thanks !

**Comment by benwaffle** [comment]
Hey @tlimoncelli, do you have any plans to tag a new version which includes this fix?

**Comment by tlimoncelli** [comment]
Thanks for the reminder.  I tagged it just now.

**Comment by benwaffle** [comment]
Since v2.0.0 was previously tagged, should the latest release be v2.0.1? Note that the homebrew package installs 2.0.0, I don't know if it will install v1.20220610 as an update

**Comment by tlimoncelli** [comment]
Oh dang.  v2.0.0 was supposed to be a parallel project in the same repo. I forgot that systems would see the v2.x and treat it as the latest release.  I should have used a name like "project2" or something.

Anyway....

I've removed the v2.0.0 and v1.1 tags from the repo entirely.   That fixes the fundamental problem.

Thanks for bringing this to my attention!

**Comment by benwaffle** [comment]
A `brew update` successfully did `blackbox 2.0.0 -> 1.20220610` for me now
