### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by jacoelho** [StackExchange/blackbox#36]
Is possible to tag a release version or a stable version? that would help creating an acceptable brew (http://brew.sh/) formula.

**Comment by tlimoncelli** [comment]
I've never worked with git tags before so let's see if  get this right :-)

I've added "stable" and "release" tags.

In the future, I'll take releases "stable" if I think they are stable and promote them to "release" a few days later if there are no complaints.

How's that?

**Comment by tlimoncelli** [comment]
Note: I've changed it to "stable" and "production".  Having a release named "release" is confusing. I've also added a file called RELEASE_ENGINEERING.TXT that explains this.
