### ISSUE TITLE
Note: It's also a bug that `action` is not being passed, but that is only for Chrome MV3. I have follow-up changes MV3 changes anyway, so will address that with those.

### ISSUE THREAD

**Issue by Hmpterockz69** [StackExchange/blackbox#371]
Note: It's also a bug that `action` is not being passed, but that is only for Chrome MV3. I have follow-up changes MV3 changes anyway, so will address that with those.

_Originally posted by @kzar in https://github.com/duckduckgo/content-scope-scripts/pull/226#discussion_r1065828692_

**Comment by tlimoncelli** [comment]
Huh?
