### ISSUE TITLE
use gpg-agent when available

### ISSUE THREAD

**Issue by stratoukos** [StackExchange/blackbox#41]
gpg has a --use-agent flag which uses the gpg agent if available. If it's not it does nothing, so users that don't care are not affected.

**Comment by tlimoncelli** [comment]
The man page says:

       --use-agent

       --no-use-agent
              This is dummy option. gpg2 always requires the agent.

Can you describe the use-case where the agent isn't being invoked?  It could be due to I/O redirection or other issue.

**Comment by stratoukos** [comment]
This seems to be a gpg vs gpg2 difference. gpg's man page says:

    --use-agent
    
    --no-use-agent
           Try to use the GnuPG-Agent.  With this option, GnuPG first tries to connect to the agent before it asks for a passphrase. --no-use-agent disables this option.

It's not a problem for me, since I can just install gpg2, but it may be worth adding the flag for gpg users. I couldn't find a clear description of their differences (best I could find was [this](http://lists.gnupg.org/pipermail/gnupg-users/2009-March/035957.html)), but both seem to be supported and some people seem to prefer gpg.

**Comment by tlimoncelli** [comment]
Since --use-agent is a no-op for gpg2, I'd gladly accept a patch that includes that option all over the place.

**Comment by onyxraven** [comment]
I think this can be closed re #64
