### ISSUE TITLE
Security implications in many scripts

### ISSUE THREAD

**Issue by Gnouc** [StackExchange/blackbox#48]
Forgetting quote variables in shell script lead to many security implications. I took a look into some blackbox scripts and found some issue.

Example in blackbox_addadmin:
```
KEYNAME="$1"
: ${KEYNAME:?ERROR: First argument must be a keyname (email address)} ;
```
It looks no harm but if someone call `blackbox_addadmin` like:

````
blackbox_addadmin '/*/*/*/*/../../../../*/*/*/*/../../../../*/*/*/*'
```
then it push server to heavy load, even if mightiest server. Imaging some command like this ran and what happen with server.

I have made a pull request to fix this, you can look [here](https://github.com/StackExchange/blackbox/pull/47)

**Comment by jw35** [comment]
Quoting the substitution of `$EDITOR` in `blackbox_edit` prevents you including arguments in `$EDITOR` (`mate -w` for the MacOS TextMate editor, for example) which appears to be commonly allowed in other similar situations. I admit I don't fully understand the implications of dropping the quoting here, but if if could be done without a significant downside it might be helpful.

**Comment by Gnouc** [comment]
@jw35 If some one set `EDITOR=/*/*/*/*/../../../../*/*/*/*/../../../../*/*/*/*`, then running script make server in heavy weight. if you want to include argument, you should at least disable glob in your script, or better using alias `alias mate="mate -w"`.
