### ISSUE TITLE
blackbox_register_new_file fails for paths with spaces [OS X]

### ISSUE THREAD

**Issue by N4M3Z** [StackExchange/blackbox#50]
Calling blackbox_register_new_file fails, if the repository path contains spaces, eg:
========== Encrypting: <filename>
========== Encrypting: DONE
  File "<string>", line 1
    import os ; print(os.path.relpath("/Users/<user>/Library/Application
                                                                       ^
SyntaxError: EOL while scanning string literal
In this case, the path contains in "Application Support" which includes spaces. I guess the issue is in get_unencrypted_filename?

blackbox_edit_start pops up a similar error message, but somehow still manages to decrypt the file and save it properly.

**Comment by Gnouc** [comment]
@N4M3Z It's a bug in `vcs_relative_path` function. I fixed in this [pull request](https://github.com/StackExchange/blackbox/pull/51)

**Comment by N4M3Z** [comment]
Yes, I see. Thank you for looking into it. Let me know if you require further testing.

**Comment by tlimoncelli** [comment]
I've merged the code that should fix this. Please take a look and report back.

**Comment by N4M3Z** [comment]
Everything seems to be working fine now, even though I got this upon calling `blackbox_register_new_file`:
```
fatal: /Users/mzeman/Library/Application: '/Users/mzeman/Library/Application' is outside repository
```

**Comment by Gnouc** [comment]
@N4M3Z It's because your file added is in the folder which outside git repository.

**Comment by N4M3Z** [comment]
I am pretty sure the file was inside the the cloned folder. Seems more like another of the filepath with spaces issues, since "/Users/mzeman/Library/Application" was actually supposed to be "/Users/mzeman/Library/Application Support/Sublime Text 3"

**Comment by Gnouc** [comment]
@N4M3Z Please checkout this [pull request](https://github.com/StackExchange/blackbox/pull/53) and report if it work

**Comment by tlimoncelli** [comment]
Fixed. Please re-opening if you find other related issues (or submit PR).
