### ISSUE TITLE
blackbox_cat and blackbox_edit require other scripts to be on $PATH

### ISSUE THREAD

**Issue by jw35** [StackExchange/blackbox#57]
blackbox_edit and blackbox_cat use other blackbox scripts internally, but assume that they will be found on $PATH. It's sometimes useful to be able to run these scripts by pathname without first putting them on $PATH, and all the other scripts work just fine in these circumstances.

I've created PR #56 to fix this.

**Comment by tlimoncelli** [comment]
PR #56 accepted.
