### ISSUE TITLE
Add support for Homebrew

### ISSUE THREAD

**Issue by ekristen** [StackExchange/blackbox#59]
Very few people use MacPorts anymore. It would be nice to see support for installing blackbox via HomeBrew. 

You'll have to refactor the blacbox_home variable to be externally set, or be able to not put the underscore scripts in the `bin` directory, that's a deal breaker for HomeBrew, they don't want any scripts going into `bin` that aren't called directly.

**Comment by tlimoncelli** [comment]
Moving the _*.sh libraries to a "lib" directory has been something I've been wanting to do for a long time. However I don't want users to have to set blackbox_home externally.  I'm open to suggestions on how to find the _*.sh files some other way.

**Comment by onyxraven** [comment]
+1 on figuring this out.  if you were to just symlink the non underscore files, would they work as is or would that path need to resolve the realpath?  (I havent tried yet, but will in just a few)

**Comment by christianbundy** [comment]
@ekristen What sort of bug would you run into without externally setting `blackbox_home`? I don't think I understand how that solves the problem.

**Comment by ekristen** [comment]
Homebrew won't allow for included in the bin folder. So we need to place the underscore files in an include path

**Comment by shadone** [comment]
Having brew package would be great! :+1:

**Comment by tlimoncelli** [comment]
@ekristen  You mean the _*.s files have to be in a 'lib' directory or something?  Any coding suggestions on how to do that in bash?

**Comment by amosshapira** [comment]
I think this can be closed: [homebrew-core blackbox formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/blackbox.rb)

**Comment by tlimoncelli** [comment]
Awesome!
