### ISSUE TITLE
$EDITOR should support additional options

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/blackbox#72]
People want to be able to do:

export EDITOR="subl -nw"

**Comment by tlimoncelli** [comment]
onyxraven proposed:
https://github.com/StackExchange/blackbox/pull/67

**Comment by tlimoncelli** [comment]
Gnouc replied with this alternative:
https://github.com/StackExchange/blackbox/pull/68

**Comment by tlimoncelli** [comment]
Gnouc, thank you for the explanation.

Two questions:

1. Why is it bad to call $EDITOR without quotes?  Normally we need to quote string variables for safety reasons. However in this case, it wouldn't let the user do anything they couldn't do to themselves. In other words it would only permit "self-inflicted injuries"/  For example, if a user can change $EDITOR to include "rm * ;", they can probably just run "rm *".  We never call "sudo $EDITOR", for example.   On the other hand, if their editor is "/Users/My Commands/foo" then "$EDITOR" will work and $EDITOR will not. However, https://github.com/StackExchange/blackbox/pull/67 nor https://github.com/StackExchange/blackbox/pull/68 would not work in that situation either.

2. Why not have the user specify $EDITOR_OPTS?  It would reduce the complexity of the code.  In fact, they could set it to a string, and then we would call: `"$EDITOR" $EDITOR_OPTS "$FILENAME"`.  As a result, EDITOR="/Users/My Commands/foo" would work, and if they wanted to put spaces and quotes in $EDITOR_OPTS, they could quote them as needed. I think the answer is" People set EDITOR="subl -nw" and it works with other systems. Therefore it should work for us.

Therefore, I believe the criteria is:

This should work: EDITOR="subl -nw"
This doesn't need to work: EDITOR="/Users/My Commands/bin/foo"

Both https://github.com/StackExchange/blackbox/pull/67 and https://github.com/StackExchange/blackbox/pull/68 work for that criteria.  Shouldn't we select the less complex solution?

**Comment by Gnouc** [comment]
@tlimoncelli I agree that we should select the less complex solution, but with careful mind. As I said, leaving variables unquote in shell script is really a bad ideal, especial those variables came from environment. `EDITOR='/*/*/*/*../../../../*/*/*/*../../../../*/*/*/*'` is an example.

I think, the best method in this case, we can disable globbing in  `blackbox_edit` with `set -f`. Then we can be safe with `EDITOR='/*/*/*/*../../../../*/*/*/*../../../../*/*/*/*'`

**Comment by fidian** [comment]
An alternative is to have a shell command that you maintain, eg `~/bin/editor`:

    #!/bin/bash
    subl -nw "$@"

Then set EDITOR to use it

    export EDITOR="$HOME/bin/editor"

**Comment by tlimoncelli** [comment]
I'm rejecting this feature request.  It can not be implemented securely.  The solution in https://github.com/StackExchange/blackbox/issues/72#issuecomment-102446596 is secure and sufficient.
