### ISSUE TITLE
Using Blackbox i am able to use diff tools? Manage merge conflict?

### ISSUE THREAD

**Issue by MrZogs** [StackExchange/blackbox#73]
Hi i'm looking for a way to use git with encrypt files without losing diff tools. Is the blackbox my solution? after i made git pull and decrypt i will be able to see merge conflict in case of existing ones?

**Comment by tlimoncelli** [comment]
The encryption gets in the way of merging and diffing. Sorry!

I've heard git-crypt does a better job of that but I haven't tried it.
