### ISSUE TITLE
/usr/bin/_blackbox_common.sh: line 265: cd: /dev/null: Not a directory

### ISSUE THREAD

**Issue by PeterGrace** [StackExchange/blackbox#75]
When trying to deploy via TeamCity with blackbox_postdeply, above error is emitted. 

Setting up bash -x to give debug info, REPOBASE is being set as /dev/null.  There isn't a .git subdirectory in the project directory.

**Comment by tlimoncelli** [comment]
The issue seems to be:

If blackbox fails outside of a Git/Svn/Hg repo.  As a user, I want to be able to decrypt files when they've been copied out of a repo.

**Comment by tlimoncelli** [comment]
This patch fixes it: 4a5787c
Waiting for verification.

**Comment by PeterGrace** [comment]
I can confirm that this change solves my issue.  Thanks Tom!
