### ISSUE TITLE
Failure in blackbox_update_all_files leaves unencrypted file on drive.

### ISSUE THREAD

**Issue by Ac0lyte** [StackExchange/blackbox#76]
If a key for a user listed in blackbox-admins.txt is not found then the re-encrypt fails leaving the unencrypted file on disk without any working.

Fixes that I can think of (not necessarily the only ones)
 - check for keys for all users prior to decryption.
 - perform the decrypt and re-encrypt in memory w/o a temp file
 - remove temp file on failure
 - warn the user that an unencrypted file was left on the drive

How to reproduce:
 - echo 'abba@notarealuser.com'  >> keyrings/live/blackbox-admins.txt
 - blackbox_update_all_files

**Comment by tlimoncelli** [comment]
If blackbox-admins.txt contains users that don't exist in the keychain, shouldn't the entire system stop?  It seems like that indicates that something is very wrong and needs human intervention to fix it.
