### ISSUE TITLE
Missing blackbox_deregister_file

### ISSUE THREAD

**Issue by fidian** [StackExchange/blackbox#84]
There's manual steps for removing a file from blackbox but it would be far better to have a tool to do it so I know that I won't screw up.  Is there a possibility of adding this feature?

**Comment by tlimoncelli** [comment]
This sounds like a great starter project!

**Comment by fidian** [comment]
What do you mean about "starter project"?

**Comment by selfcommit** [comment]
@fidian A starter project would be something small and easy that a new contributor could create a pull request for.  
@tlimoncelli If @fidian is not interested I'd be happy to take a swing this weekend.

**Comment by fidian** [comment]
Closing this because #85 was merged.
