### ISSUE TITLE
make packages-dev uses wrong arch

### ISSUE THREAD

**Issue by jvasile** [StackExchange/blackbox#86]
I did a gem install fpm, then make packages-deb and I got an AMD64 deb.

$ ls ~/debbuild-stack_blackbox/
bin-packages.txt  installroot  stack-blackbox_1.0-1_amd64.deb
$ uname -m
x86_64.

Maybe this is a bug in fpm, but since you depend on it, it's your bug too!

Thanks.

**Comment by tlimoncelli** [comment]
Turns out fpm's `-a` option takes a value `all` which translates to "noarch" or whatever it should be for that system. 

Fixed!
