### ISSUE TITLE
recommendation on how to protect releases?

### ISSUE THREAD

**Issue by jackxxu** [StackExchange/blackbox#94]
Do we have any guidelines or best-practices on how to best protect secrets in releases, such as in a .war file? one approach that comes to mind is encrypting the releases as well, such as creating an encrypted war file, however, it will involve the release management personnel be added as blackbox admins.

**Comment by tlimoncelli** [comment]
Some suggestions:
1.  Keep a separate git repo for the release management personnel.
2.   Implement the suggestion for a per-directory key chain (see https://github.com/StackExchange/blackbox/issues/8)
3.  Don't check releases into Git.  Store them in a package repo or other facility.

I don't want to tell you how to run your company, but if your release package includes unencrypted secrets, then you are doing it wrong.  You now have to protect that release package in Git, in the package repo, when transferring it to the machine it will be installed on, and so on.  That can be quite a burden.  Are all machines and networks along that path trusted?  (this is called "the trusted path" problem).

What we do at Stack is our release packages include no secrets, but if a secret is needed we use Puppet to install it.

You might also consider moving all secrets to a different package. This 2nd package then receives special treatment (encryption, and so on).  Many years ago (before Git) I worked at a company that did that.  The 2nd package could either be the one with real secrets, or a package of "test secrets" that only worked in our test environment.

Just some thoughts.

Hope that helps!

**Comment by jackxxu** [comment]
thanks, @tlimoncelli. it is very helpful.
