### ISSUE TITLE
Support for multiple blackboxes in a single repo?

### ISSUE THREAD

**Issue by dialt0ne** [StackExchange/blackbox#99]
This is more of a question than an issue but...

Can I host more than 1 blackbox in a repository?

From looking at the code (_blackbox_common.sh) it seems that if I set the env variable BLACKBOXDATA before invoking, I can create multiple blackboxes e.g.

export BLACKBOXDATA=keyrings/prod
(some blackbox commands)
export BLACKBOXDATA=keyrings/dev
(somre different blackbox commands)

etc. etc. Mostly, before I go using this feature, I want to insure that this functionality is intended vs. a happy accident that will be deprecated later.

Thanks!

**Comment by tlimoncelli** [comment]
This question is similar to https://github.com/StackExchange/blackbox/issues/8

The short answer is: It isn't supported at this time.

The long answer is: It used to be nearly impossible.  With recent code changes, especially the BLACKBOXDATA variable you mentioned, it should be much easier.  In fact, you play around with that variable and find bugs, please report them.

The big issue is how does one select which set of keys?  Should the blackbox_* commands simply not change BLACKBOXDATA if it is already set?  Should there be a variable that defaults to "prod" if unset, but otherwise lets you select another directory within "keyrings"?  How should blackbox_decrypt_all_files work?  Should blackbox_register_new_file give an error if the file is already listed in a different blackbox-files.txt file?

**Comment by dialt0ne** [comment]
If you start with the assumptions:

* one blackbox should not know (or care) about other blackboxes
* no file should be in two blackboxes at the same time

setting `BLACKBOXDATA` to `keyrings/prod` vs. `keyrings/dev` looks to work ok. The per-keyring blackbox-admins.txt and blackbox-files.txt track the necessary info. It also works if I set BLACKBOXDATA and then run `tools/confidence_test.sh`, after the test script is lightly modified. Specifically:

a) I changed `keyrings/live` to `$BLACKBOXDATA` everywhere
b) I commented out calls to `assert_file_group` because there's a bug in it if the group name has a space in it (using OSX)

I guess the real trick is enforcing the assumption that no file should attempt to be in multiple blackboxes at the same time.

**Comment by tlimoncelli** [comment]
I agree with those assumptions.

Would you consider sending a patch?

There are many ways to tell if a file is listed twice.  One would be:
```
( echo "$NEWFILENAME" ; cat keyrings/*/blackbox-files.txt ) | sort | uniq -c | awk '$1 > 1 { exit 1}'
```

**Comment by dialt0ne** [comment]
I will try to work up a patch for `keyrings/live` to `$BLACKBOXDATA`

As I don't have a set of test platforms, I'm unsure of the right way to solve the issue with `assert_file_group` in a cross-platform compatible way. The sanitized error on my OSX box that's using Active Directory is:

```
ASSERT FAILED: secret.txt chgrp wanted=EXAMPLE\Domain Users found=EXAMPLE\Domain
```
And the issues is obvious when looking at a sample file:
```
$ ls -lg foo
-rw-r--r--  1 EXAMPLE\Domain Users  0 Jun 30 15:06 foo
```
e.g. `awk '{ print $3 }'` doesn't cut it. There's a comment about not using stat because it would break on BSD-style OSs, but it's also broken where groups can have spaces in them :-\

**Comment by tlimoncelli** [comment]
I just committed a change to assert_file_group that should work if there is a space in the GID name. Give it a try.

**Comment by tlimoncelli** [comment]
@dialt0ne friendly ping?

**Comment by dialt0ne** [comment]
When I mentioned "It also works if I set BLACKBOXDATA and then run tools/confidence_test.sh", it seems that I was working off a fork of a previous edition and not the current edition. I have not had the opportunity to bring our company's fork up to current to test. I will try out the latest in a Linux VM.

**Comment by tlimoncelli** [comment]
There is now a env variable named BLACKBOXDATA that selects this. If it is unset, it defaults to "keyrings/live".  You can set it to (for example) keyrings/test and "blackbox_initialize" a new keychain there, and encrypt files using that keychain.  You must be careful to have the different keychains encrypt disjoint sets of files.  Switching the environment variable is manual.
